SAMPLE_RATE = 44100
CHUNK_SIZE = 1024  # one FFT frame
CHANNELS = 1
WINDOW_TYPE = "hann"  # hann / hamming / rectangular
DB_MIN = -60.0
DB_MAX = 0.0
WATERFALL_HISTORY = 200
COLORMAP = "inferno"
TARGET_FPS = 30

# pitch overlay
PITCH_FMIN = 60.0
PITCH_FMAX = 1200.0
PITCH_CONFIDENCE_MIN = 0.45
PITCH_RMS_MIN = 0.01
PITCH_SMOOTHING_FRAMES = 5

DEFAULT_SOURCE = "mic"  # or "loopback"